[package]
name = "it_initial_file_system"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
ctor = { workspace = true }
golem-rust = { workspace = true }
golem-wasi-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wstd = { workspace = true }
