enable_tracing_console = false
enable_json_log = false
number_of_shards = 1024
http_port = 8081

rebalance_threshold = 0.1

[redis]
host = "localhost"
port = 6380
database = 0
tracing = false
pool_size = 8
key_prefix = ""

[redis.retries]
max_attempts = 5
min_delay = "100ms"
max_delay = "2s"
multiplier = 2

[worker_executors]
assign_shards_timeout = "5s"
health_check_timeout = "2s"
revoke_shards_timeout = "5s"

[worker_executors.retries]
max_attempts = 5
min_delay = "100ms"
max_delay = "2s"
multiplier = 2

[health_check]
delay = "10s"

[health_check.mode]
type = "Grpc"
#type = "K8s"

[health_check.mode.config]
#namespace = "default"
