[workspace]
resolver = "2"
members = ["components-rust/*", "common-rust/*"]

[profile.release]
opt-level = "s"
lto = true

[workspace.dependencies]

golem-rust = { path = "../../sdks/rust/golem-rust", features = [
    "export_golem_agentic",
#    "golem_ai" # Uncomment to use Golem AI libraries
] }

# Advanced HTTP client, alternative of wstd::http
golem-wasi-http = { version = "0.1.0", features = ["json"] }

futures-concurrency = "7.6.3"
wasi = { version = "=0.14.1+wasi-0.2.3" }
log = { version = "0.4.29", features = ["kv"] }
rand = "0.9.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wstd = {version = "=0.5.4", features = ["default", "json"] }
