[package]
name = "child-component"
version = "0.0.1"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"


[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'
strip = true

[dependencies]
once_cell = "1.17.1"
rand = "0.8.5"
wit-bindgen = { version = "0.17.0", default-features = false, features = ["realloc"] }
common = { path = "../../common" }

[package.metadata.component.target]
path = "wit"

[package.metadata.component.dependencies]
