[package]
name = "golem-worker-bridge"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
description = "Worker Bridge acts as a bridge between external API gateways and the worker's environment"


[[bin]]
name = "golem-worker-bridge"
path = "src/main.rs"


[dependencies]
golem-common = { path = "../golem-common" }
golem-api-grpc = { path = "../golem-api-grpc" }

async-trait = { workspace = true }
regex = "1.10.3"
bincode = "2.0.0-rc.3"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
serde_yaml = "0.9.31"
strum = "0.26.1"
strum_macros = "0.26.1"
poem = { workspace = true, features = ["prometheus", "opentelemetry"] }
poem-openapi = { workspace = true }
derive_more = "0.99.17"
uuid = { workspace = true }
nom = "7.1.3"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt", "std", "json"] }
http = "1.0.0"
tonic = "0.10.2"
figment = { workspace = true }
url = { workspace = true }
http_02 = { package = "http", version = "0.2.11" }
hyper = { workspace = true }
bytes = { workspace = true }
tokio = { workspace = true }
prometheus = "0.13.3"
futures = "0.3.30"
