version: '3.8'

services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  golem-shard-manager:
    build:
      context: .
      dockerfile: golem-shard-manager/docker/Dockerfile
    environment:
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__REDIS__HOST=redis
      - GOLEM__REDIS__PORT=${REDIS_PORT}
      - GOLEM__HTTP_PORT=${SHARD_MANAGER_HTTP_PORT}
      - GOLEM_SHARD_MANAGER_PORT=${SHARD_MANAGER_GRPC_PORT}
    depends_on:
      - redis

  golem-service:
    build:
      context: .
      dockerfile: golem-service/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__TEMPLATES__STORE__TYPE="Local"
      - GOLEM__TEMPLATES__STORE__CONFIG__OBJECT_PREFIX=""
      - GOLEM__TEMPLATES__STORE__CONFIG__ROOT_PATH=/template_store
      - GOLEM__DB__TYPE=Sqlite
      - GOLEM__DB__CONFIG__DATABASE=/app/golem_db/golem.sqlite
      - GOLEM__DB__CONFIG__MAX_CONNECTIONS=10
      - GOLEM__ROUTING_TABLE__HOST="golem-shard-manager"
      - GOLEM__ROUTING_TABLE__PORT=${SHARD_MANAGER_GRPC_PORT}
      - GOLEM__GRPC_PORT=${GOLEM_SERVICE_GRPC_PORT}
      - GOLEM__HTTP_PORT=${GOLEM_SERVICE_HTTP_PORT}
    volumes:
      - template_store:/template_store
      - golem_db:/app/golem_db
    ports:
      - "${GOLEM_SERVICE_HTTP_PORT}:${GOLEM_SERVICE_HTTP_PORT}"
      - "${GOLEM_SERVICE_GRPC_PORT}:${GOLEM_SERVICE_GRPC_PORT}"

  golem-worker-bridge:
    build:
      context: .
      dockerfile: golem-worker-bridge/docker/Dockerfile
    pull_policy: always
    environment:
      - GOLEM__REDIS__HOST=redis
      - GOLEM__REDIS__PORT=${REDIS_PORT}
      - GOLEM__REDIS__DATABASE=1
      - GOLEM__ENVIRONMENT=local
      - GOLEM__TEMPLATE_SERVICE__HOST=golem-service
      - GOLEM__TEMPLATE_SERVICE__PORT=${GOLEM_SERVICE_GRPC_PORT}
      - GOLEM__TEMPLATE_SERVICE__ACCESS_TOKEN='5C832D93-FF85-4A8F-9803-513950FDFDB1"
      - GOLEM_SHARD_MANAGER_PORT=${SHARD_MANAGER_GRPC_PORT}
    depends_on:
      - redis

  golem-worker-executor:
    build:
      context: .
      dockerfile: golem-worker-executor/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info
      - GOLEM__REDIS__PORT=${REDIS_PORT}
      - GOLEM__REDIS__HOST=redis
      - GOLEM__TEMPLATE_SERVICE__CONFIG__HOST=golem-service
      - GOLEM__TEMPLATE_SERVICE__CONFIG__PORT=${GOLEM_SERVICE_GRPC_PORT}
      - GOLEM__TEMPLATE_SERVICE__CONFIG__ACCESS_TOKEN="2A354594-7A63-4091-A46B-CC58D379F677"
      - GOLEM__PORT=${WORKER_EXECUTOR_GRPC_PORT}
      - GOLEM__HTTP_PORT=${WORKER_EXECUTOR_HTTP_PORT}
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__HOST=golem-shard-manager
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__PORT=${SHARD_MANAGER_GRPC_PORT}
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_ATTEMPTS=5
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MIN_DELAY="100ms"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_DELAY="2s"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MULTIPLIER=2
      - GOLEM__BLOB_STORE_SERVICE__CONFIG__REGION=us-east-1
      - GOLEM__COMPILED_TEMPLATE_SERVICE__CONFIG__ROOT="data/templates"
      - GOLEM__COMPILED_TEMPLATE_SERVICE__TYPE="Local"
      - GOLEM__SHARD_MANAGER_SERVICE__TYPE="Grpc"
    ports:
      - "${WORKER_EXECUTOR_HTTP_PORT}:${WORKER_EXECUTOR_HTTP_PORT}"

volumes:
  redis_data:
    driver: local
  template_store:
    driver: local
  golem_db:
    driver: local