version: '3'

services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: golem_db
      POSTGRES_USER: golem_user
      POSTGRES_PASSWORD: golem_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  golem-shard-manager:
    build:
      context: .
      dockerfile: golem-shard-manager/docker/Dockerfile
    environment:
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__REDIS__HOST=redis
      - GOLEM__REDIS__PORT=6379
      - GOLEM__HTTP_PORT=8081
      - GOLEM_SHARD_MANAGER_PORT=9001
    ports:
      - "8081:8081"
    depends_on:
      - redis

  golem-cloud-server-oss:
    build:
      context: .
      dockerfile: golem-cloud-server-oss/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - RUST_LOG="debug,h2=warn,hyper=warn,tower=warn"
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__TEMPLATES__STORE__TYPE="Local"
      - GOLEM__TEMPLATES__STORE__CONFIG__OBJECT_PREFIX=""
      - GOLEM__TEMPLATES__STORE__CONFIG__ROOT_PATH=/template_store
      - GOLEM__DB__TYPE=Postgres
      - GOLEM__DB__CONFIG__DATABASE=golem_db
      - GOLEM__DB__CONFIG__MAX_CONNECTIONS=10
      - GOLEM__DB__CONFIG__HOST=postgres
      - GOLEM__DB__CONFIG__USERNAME=golem_user
      - GOLEM__DB__CONFIG__PASSWORD=golem_password
      - GOLEM__ROUTING_TABLE__HOST="golem-shard-manager"
      - GOLEM__ROUTING_TABLE__PORT=9001
      - GOLEM__GRPC_PORT=9090
      - GOLEM__HTTP_PORT=8080
    volumes:
      - template_store:/template_store
    ports:
      - "8080:8080"
      - "9090:9090"
      - "9001:9001"
    depends_on:
      - postgres

  golem-worker-executor-oss:
    build:
      context: .
      dockerfile: golem-worker-executor-oss/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - RUST_LOG=info
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__REDIS__PORT=6379
      - GOLEM__REDIS__HOST=redis
      - GOLEM__TEMPLATE_SERVICE__CONFIG__HOST=golem-cloud-server-oss
      - GOLEM__TEMPLATE_SERVICE__CONFIG__PORT=9090
      # This is a dummy access id, didn't want to change the base golem-config as I am not aware of what's the implication
      - GOLEM__TEMPLATE_SERVICE__CONFIG__ACCESS_TOKEN="2A354594-7A63-4091-A46B-CC58D379F677"
      - GOLEM__PORT=9000
      - GOLEM__HTTP_PORT=8082
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__HOST=golem-shard-manager
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__PORT=9001
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_ATTEMPTS=5
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MIN_DELAY="100ms"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_DELAY="2s"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MULTIPLIER=2
      - GOLEM__BLOB_STORE_SERVICE__CONFIG__REGION=us-east-1
      - GOLEM__COMPILED_TEMPLATE_SERVICE__CONFIG__ROOT="data/templates"
      - GOLEM__COMPILED_TEMPLATE_SERVICE__TYPE="Local"
      - GOLEM__SHARD_MANAGER_SERVICE__TYPE="Grpc"
      - AWS_SECRET_ACCESS_KEY=root
      - AWS_ACCESS_KEY_ID=root
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "9000:9000"

volumes:
  redis_data:
    driver: local
  template_store:
    driver: local
  postgres_data:
    driver: local