version: '3'

services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  golem-shard-manager:
    build:
      context: .
      dockerfile: golem-shard-manager/docker/Dockerfile
    environment:
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__REDIS__HOST=redis
      - GOLEM__REDIS__PORT=6379
      - GOLEM__HTTP_PORT=8081
      - GOLEM_SHARD_MANAGER_PORT=9001
    ports:
      - "8081:8081"
    depends_on:
      - redis

  golem-cloud-server-oss:
    build:
      context: .
      dockerfile: golem-cloud-server-oss/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__TEMPLATES__STORE__TYPE="Local"
      - GOLEM__TEMPLATES__STORE__CONFIG__OBJECT_PREFIX=""
      - GOLEM__TEMPLATES__STORE__CONFIG__ROOT_PATH=/template_store
      - GOLEM__DB__DATABASE=/app/golem_db/golem.sqlite
      - GOLEM__ROUTING_TABLE__HOST="golem-shard-manager"
      - GOLEM__ROUTING_TABLE__PORT=9001
      - GOLEM__GRPC_PORT=9090
      - GOLEM__HTTP_PORT=8080
    volumes:
      - template_store:/template_store
      - golem_db:/app/golem_db
    ports:
      - "8080:8080"
      - "9090:9090"
      - "9001:9001"

  golem-worker-executor-oss:
    build:
      context: .
      dockerfile: golem-worker-executor-oss/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info
      - GOLEM__REDIS__PORT=6379
      - GOLEM__REDIS__HOST=redis
      - GOLEM__TEMPLATE_SERVICE__CONFIG__HOST=golem-cloud-server-oss
      - GOLEM__TEMPLATE_SERVICE__CONFIG__PORT=9090
        # This is a dummy access id, didn't want to change the base golem-config as I am not aware of what's the implication
      - GOLEM__TEMPLATE_SERVICE__CONFIG__ACCESS_TOKEN="2A354594-7A63-4091-A46B-CC58D379F677"
      - GOLEM__PORT=9000
      - GOLEM__HTTP_PORT=8082
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__HOST=golem-shard-manager
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__PORT=9001
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_ATTEMPTS=5
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MIN_DELAY="100ms"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_DELAY="2s"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MULTIPLIER=2
      - GOLEM__BLOB_STORE_SERVICE__CONFIG__REGION=us-east-1
      - GOLEM__COMPILED_TEMPLATE_SERVICE__CONFIG__ROOT="data/templates"
      - GOLEM__COMPILED_TEMPLATE_SERVICE__TYPE="Local"
      - GOLEM__SHARD_MANAGER_SERVICE__TYPE="Grpc"
    ports:
      - "9000:9000"

volumes:
  redis_data:
    driver: local
  template_store:
    driver: local
  golem_db:
    driver: local