version: "3.8"

services:
  router:
    build:
      context: .
      dockerfile: golem-router/docker/Dockerfile
    # Note that, golem_gateway_port should be changed carefully
    # as it is currently set to match the default port in golem-cli:
    # Golem base url. Default: GOLEM_BASE_URL environment variable or http://localhost:9881
    ports:
      - "${GOLEM_ROUTER_PORT}:80"
    environment:
      - GOLEM_COMPONENT_MAX_SIZE_ALLOWED=${GOLEM_ROUTER_COMPONENT_MAX_SIZE_ALLOWED}
      - GOLEM_WORKER_SERVICE_HOST=golem-worker-service
      - GOLEM_WORKER_SERVICE_PORT=${WORKER_SERVICE_HTTP_PORT}
      - GOLEM_COMPONENT_SERVICE_HOST=golem-component-service
      - GOLEM_COMPONENT_SERVICE_PORT=${COMPONENT_SERVICE_HTTP_PORT}
    depends_on:
      - golem-worker-service
      - golem-component-service
      - golem-shard-manager

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    command: --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  golem-shard-manager:
    build:
      context: .
      dockerfile: golem-shard-manager/docker/Dockerfile
    environment:
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__REDIS__HOST=redis
      - GOLEM__REDIS__PORT=${REDIS_PORT}
      - GOLEM__HTTP_PORT=${SHARD_MANAGER_HTTP_PORT}
      - GOLEM_SHARD_MANAGER_PORT=${SHARD_MANAGER_GRPC_PORT}
    depends_on:
      - redis

  golem-component-service:
    build:
      context: .
      dockerfile: golem-component-service/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__COMPONENT_STORE__TYPE="Local"
      - GOLEM__COMPONENT_STORE__CONFIG__OBJECT_PREFIX=""
      - GOLEM__COMPONENT_STORE__CONFIG__ROOT_PATH=/component_store
      - GOLEM__COMPILATION__TYPE="Enabled"
      - GOLEM__COMPILATION__CONFIG__HOST=golem-component-compilation-service
      - GOLEM__COMPILATION__CONFIG__PORT=${COMPONENT_COMPILATION_SERVICE_GRPC_PORT}
      - GOLEM__DB__TYPE=Sqlite
      - GOLEM__DB__CONFIG__DATABASE=/app/golem_db/golem_component.sqlite
      - GOLEM__DB__CONFIG__MAX_CONNECTIONS=10
      - GOLEM__GRPC_PORT=${COMPONENT_SERVICE_GRPC_PORT}
      - GOLEM__HTTP_PORT=${COMPONENT_SERVICE_HTTP_PORT}
    volumes:
      - component_store:/component_store
      - golem_db:/app/golem_db
    ports:
      - "${COMPONENT_SERVICE_HTTP_PORT}:${COMPONENT_SERVICE_HTTP_PORT}"
      - "${COMPONENT_SERVICE_GRPC_PORT}:${COMPONENT_SERVICE_GRPC_PORT}"

  golem-worker-service:
    build:
      context: .
      dockerfile: golem-worker-service/docker/Dockerfile
    pull_policy: always
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__DB__TYPE=Sqlite
      - GOLEM__DB__CONFIG__DATABASE=/app/golem_db/golem_worker.sqlite
      - GOLEM__DB__CONFIG__MAX_CONNECTIONS=10
      - GOLEM__ENVIRONMENT=local
      - GOLEM__COMPONENT_SERVICE__HOST=golem-component-service
      - GOLEM__COMPONENT_SERVICE__PORT=${COMPONENT_SERVICE_GRPC_PORT}
      - GOLEM__COMPONENT_SERVICE__ACCESS_TOKEN="5C832D93-FF85-4A8F-9803-513950FDFDB1"
      - GOLEM__ROUTING_TABLE__HOST="golem-shard-manager"
      - GOLEM__ROUTING_TABLE__PORT=${SHARD_MANAGER_GRPC_PORT}
      - GOLEM__CUSTOM_REQUEST_PORT=${WORKER_SERVICE_CUSTOM_REQUEST_PORT}
      - GOLEM__PORT=${WORKER_SERVICE_HTTP_PORT}
      - GOLEM__WORKER_GRPC_PORT=${WORKER_SERVICE_GRPC_PORT}
    ports:
      - "${WORKER_SERVICE_HTTP_PORT}:${WORKER_SERVICE_HTTP_PORT}"
      - "${WORKER_SERVICE_CUSTOM_REQUEST_PORT}:${WORKER_SERVICE_CUSTOM_REQUEST_PORT}"
      - "${WORKER_SERVICE_GRPC_PORT}:${WORKER_SERVICE_GRPC_PORT}"
    volumes:
      - golem_db:/app/golem_db

  golem-component-compilation-service:
    build:
      context: .
      dockerfile: golem-component-compilation-service/docker/Dockerfile
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info,h2=warn,hyper=warn,tower=warn
      - GOLEM__BLOB_STORAGE__TYPE="LocalFileSystem"
      - GOLEM__BLOB_STORAGE__CONFIG__ROOT="/component_compiled_store"
      - GOLEM__COMPONENT_SERVICE__HOST=golem-component-service
      - GOLEM__COMPONENT_SERVICE__PORT=${COMPONENT_SERVICE_GRPC_PORT}
      - GOLEM__COMPONENT_SERVICE__ACCESS_TOKEN="5C832D93-FF85-4A8F-9803-513950FDFDB1"
      - GOLEM__COMPILED_COMPONENT_SERVICE__TYPE="Enabled"
      - GOLEM__HTTP_PORT=${COMPONENT_COMPILATION_SERVICE_HTTP_PORT}
      - GOLEM__GRPC_PORT=${COMPONENT_COMPILATION_SERVICE_GRPC_PORT}
    volumes:
      - component_compiled_store:/component_compiled_store
    ports:
      - "${COMPONENT_COMPILATION_SERVICE_HTTP_PORT}:${COMPONENT_COMPILATION_SERVICE_HTTP_PORT}"
      - "${COMPONENT_COMPILATION_SERVICE_GRPC_PORT}:${COMPONENT_COMPILATION_SERVICE_GRPC_PORT}"
    depends_on:
      - golem-component-service

  golem-worker-executor:
    build:
      context: .
      dockerfile: golem-worker-executor/docker/Dockerfile
    environment:
      - ENVIRONMENT=local
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - RUST_LOG=info
      - GOLEM__KEY_VALUE_STORAGE__TYPE="Redis"
      - GOLEM__KEY_VALUE_STORAGE__CONFIG__PORT=${REDIS_PORT}
      - GOLEM__KEY_VALUE_STORAGE__CONFIG__HOST=redis
      - GOLEM__INDEXED_STORAGE__TYPE="KVStoreRedis"
      - GOLEM__BLOB_STORAGE__TYPE="LocalFileSystem"
      - GOLEM__BLOB_STORAGE__CONFIG__ROOT="/component_compiled_store"
      - GOLEM__COMPONENT_SERVICE__CONFIG__HOST=golem-component-service
      - GOLEM__COMPONENT_SERVICE__CONFIG__PORT=${COMPONENT_SERVICE_GRPC_PORT}
      - GOLEM__COMPONENT_SERVICE__CONFIG__ACCESS_TOKEN="2A354594-7A63-4091-A46B-CC58D379F677"
      - GOLEM__PORT=${WORKER_EXECUTOR_GRPC_PORT}
      - GOLEM__HTTP_PORT=${WORKER_EXECUTOR_HTTP_PORT}
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__HOST=golem-shard-manager
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__PORT=${SHARD_MANAGER_GRPC_PORT}
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_ATTEMPTS=5
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MIN_DELAY="100ms"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_DELAY="2s"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MULTIPLIER=2
      - GOLEM__PUBLIC_WORKER_API__HOST=golem-worker-service
      - GOLEM__PUBLIC_WORKER_API__PORT=${WORKER_SERVICE_GRPC_PORT}
      - GOLEM__PUBLIC_WORKER_API__ACCESS_TOKEN="2A354594-7A63-4091-A46B-CC58D379F677"
      - GOLEM__COMPILED_COMPONENT_SERVICE__TYPE="Enabled"
      - GOLEM__SHARD_MANAGER_SERVICE__TYPE="Grpc"
    volumes:
      - component_compiled_store:/component_compiled_store
    ports:
      - "${WORKER_EXECUTOR_HTTP_PORT}:${WORKER_EXECUTOR_HTTP_PORT}"
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
  component_store:
    driver: local
  golem_db:
    driver: local
  component_compiled_store:
    driver: local
