[package]
name = "golem-cli"
version = "0.0.0"
edition = "2021"
homepage = "https://golem.cloud/"
repository = "https://github.com/golemcloud/golem"
description = "Command line interface for Golem."
license-file = "../../LICENSE"

autotests = false
build = "build.rs"

[features]
default = []
server-commands = []

[lib]
harness = false

[[bin]]
name = "golem-cli"
path = "src/main.rs"
test = false

[[test]]
name = "integration"
path = "tests/lib.rs"
test = true
harness = false

[dependencies]
golem-client = { workspace = true }
golem-common = { workspace = true, default-features = true }
golem-wasm = { workspace = true, default-features = true }

# External deps
anyhow = { workspace = true }
ariadne = { workspace = true }
async-trait = { workspace = true }
async_zip = { workspace = true }
base64 = { workspace = true }
blake3 = { workspace = true }
bytes = { workspace = true }
camino = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
clap-verbosity-flag = { workspace = true }
clap_complete = { workspace = true }
cli-table = { workspace = true }
colored = { workspace = true }
crossbeam-channel = { workspace = true }
desert_rust = { workspace = true }
dirs = { workspace = true }
evcxr = { workspace = true }
fs_extra = { workspace = true }
futures-util = { workspace = true }
fuzzy-matcher = { workspace = true }
gag = { workspace = true }
heck = { workspace = true }
humansize = { workspace = true }
include_dir = { workspace = true }
indexmap = { workspace = true }
indoc = { workspace = true }
inquire = { workspace = true }
iso8601 = { workspace = true }
itertools = { workspace = true }
jsonschema = { workspace = true }
lenient_bool = { workspace = true }
minijinja = { workspace = true }
moonbit-component-generator = { workspace = true }
native-tls = { workspace = true }
phf = { workspace = true }
prettyplease = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rustyline = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
shadow-rs = { workspace = true }
shlex = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
syn = { workspace = true }
synoptic = { workspace = true }
tempfile = { workspace = true }
terminal_size = { workspace = true }
textwrap = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
toml_edit = { workspace = true }
tracing = { workspace = true }
tracing-log = "0.2.0"
tracing-subscriber = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-json = { workspace = true }
tree-sitter-rust = { workspace = true }
tree-sitter-typescript = { workspace = true }
tree-sitter-yaml = { workspace = true }
unicode-segmentation = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
version-compare = { workspace = true }
wac-graph = { workspace = true }
walkdir = { workspace = true }
wax = { workspace = true }
wasm-metadata = { workspace = true }
wasm-rquickjs = { workspace = true }
wasmtime-wasi = { workspace = true }
wit-component = { workspace = true }
wit-parser = { workspace = true }

[target.'cfg(not(any(target_os = "windows", target_vendor = "apple")))'.dependencies]
openssl = { workspace = true }
openssl-sys = { workspace = true }

[dev-dependencies]
axum = { workspace = true }
goldenfile = { workspace = true }
log = { workspace = true }
pretty_assertions = { workspace = true }
pretty_env_logger = { workspace = true }
reqwest = { workspace = true }
strip-ansi-escapes = { workspace = true }
test-r = { workspace = true }

[build-dependencies]
lenient_bool = { workspace = true }
shadow-rs = { workspace = true }
