[package]
name = "golem-shard-manager"
version = "0.0.0"
edition = "2021"

license-file = "../LICENSE"

[lib]
path = "src/lib.rs"
harness = false

[[bin]]
name = "golem-shard-manager"
path = "src/server.rs"
harness = false
test = false

[dependencies]
golem-api-grpc = { workspace = true }
golem-common = { workspace = true, default-features = true }
golem-service-base = { workspace = true }

anyhow = { workspace = true }
async-rwlock = { workspace = true }
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
fred = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
humantime-serde = { workspace = true }
itertools = { workspace = true }
k8s-openapi = { workspace = true, optional = true }
kube = { workspace = true, optional = true }
prometheus = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tonic-reflection = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tracing-test = { workspace = true }
test-r = { workspace = true }

[features]
default = ["kubernetes"]
kubernetes = ["dep:kube", "dep:k8s-openapi"]
