[package]
name = "golem-shard-manager"
version = "0.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "golem-shard-manager"
path = "src/server.rs"

[dependencies]
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0" }
golem-common = { path = "../golem-common", version = "0.0.0" }

anyhow = { workspace = true }
async-rwlock = "1.3.0"
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
figment = { workspace = true }
fred = { workspace = true }
futures = { workspace = true }
http = { workspace = true }
http_02 = { workspace = true }
humantime-serde = { workspace = true }
k8s-openapi = { workspace = true, optional = true }
kube = { workspace = true, optional = true }
prometheus = { workspace = true }
prost = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tonic-reflection = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
warp = { workspace = true }

[dev-dependencies]
tracing-test = "0.2.4"

[features]
default = ["kubernetes"]
kubernetes = ["dep:kube", "dep:k8s-openapi"]
