[package]
name = "auction-stub"
edition = "2021"
version = "0.0.1"

[package.metadata.component]
package = "auction:auction"

[package.metadata.component.target]
world = "wasm-rpc-stub-auction"
path = "wit"

[package.metadata.component.target.dependencies."auction:auction"]
path = "wit/deps/auction_auction"

[package.metadata.component.target.dependencies."golem:rpc"]
path = "wit/deps/wasm-rpc"

[dependencies.golem-wasm-rpc]
version = "0.0.25"
features = ["stub"]
default-features = false

[dependencies.wit-bindgen]
version = "0.17.0"
features = ["realloc"]
default-features = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
required-features = []

[profile.release]
opt-level = "s"
lto = true
strip = true
