[package]
name = "golem-cli"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://www.golem.cloud/"
authors = ["Simon Popugaev <simon.popugaev@ziverge.com>"]
readme = "README.md"
description = "Command line interface for Golem Cloud"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
chrono = "0.4.31"
clap = { version = "4.4.6", features = ["derive"] }
clap-verbosity-flag = "2.0.1"
derive_more = "0.99.17"
futures-util = "0.3.28"
golem-client = "0.0.47"
golem-gateway-client = "0.0.47"
golem-examples = "0.1.8"
http = "0.2.9"
indoc = "2.0.4"
itertools = "0.11.0"
native-tls = "0.2.11"
reqwest = "0.11.22"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
serde_yaml = "0.9.25"
strum = "0.25.0"
strum_macros = "0.25.3"
tokio = { version = "1.33.0", features = ["full"] }
tokio-tungstenite = { version = "0.20.1", features = ["native-tls"] }
tracing = "0.1.40"
tungstenite = "0.20.1"
url = "2.4.1"
uuid = "1.5.0"
dirs = "5.0.1"
tracing-subscriber = "0.3.17"
