[package]
name = "golem-service-base"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
golem-common = { path = "../golem-common", version = "0.0.0" }
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0" }

async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
bigdecimal = "0.4.2"
http = { workspace = true }
http_02 = { package="http", version = "0.2.11" }
hyper = { workspace = true }
num-traits = "0.2"
poem-openapi = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }