[package]
name = "golem-service-base"
version = "0.0.0"
edition = "2021"

homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem"
description = "Shared code between Golem services"

license-file = "../LICENSE"

autotests = false

[lib]
harness = false

[dependencies]
golem-api-grpc = { path = "../golem-api-grpc", version = "=0.0.0" }
golem-common = { path = "../golem-common", version = "=0.0.0" }
golem-wasm-ast = { path = "../wasm-ast", version = "=0.0.0" }
golem-wasm-rpc = { path = "../wasm-rpc", version = "=0.0.0", default-features = false, features = [
    "host",
] }
golem-wasm-rpc-derive = { path = "../wasm-rpc-derive", version = "=0.0.0" }

anyhow = { workspace = true }
async-fs = { workspace = true }
async-hash = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
bincode = { workspace = true }
bitflags = "2.6.0"
bytes = { workspace = true }
chrono = { workspace = true }
conditional-trait-gen = { workspace = true }
dashmap = { workspace = true }
figment = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
humantime-serde = { workspace = true }
lazy_static = { workspace = true }
pin-project = "1.1.10"
poem = { workspace = true }
poem-openapi = { workspace = true }
poem-openapi-derive = { workspace = true }
prometheus = { workspace = true }
prost-types = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [
    "runtime-tokio",
    "sqlite",
    "postgres",
    "uuid",
    "migrate",
    "chrono",
] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
assert2 = { workspace = true }
tempfile = { workspace = true }
test-r = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
tryhard = { workspace = true }
uuid = { workspace = true }

[[test]]
name = "integration"
path = "tests/lib.rs"
harness = false
