[package]
name = "golem-service-base"
version = "0.0.0"
edition = "2021"

homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem"
description = "Shared code between Golem services"

license-file = "../LICENSE"

autotests = false

[lib]
harness = false

[features]
default = []
worker-executor = [ "dep:wasmtime-wasi" ]

[dependencies]
golem-api-grpc = { workspace = true }
golem-common = { workspace = true }
golem-wasm = { workspace = true }
golem-wasm-derive = { workspace = true }

anyhow = { workspace = true }
applying = { workspace = true }
async-fs = { workspace = true }
async-hash = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
bincode = { workspace = true }
bitflags = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
conditional-trait-gen = { workspace = true }
figment = { workspace = true }
futures = { workspace = true }
headers = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
http-body-util = { workspace = true }
humantime-serde = { workspace = true }
include_dir = { workspace = true }
lazy_static = { workspace = true }
pin-project = { workspace = true }
poem = { workspace = true }
poem-openapi = { workspace = true }
poem-openapi-derive = { workspace = true }
prometheus = { workspace = true }
prost-types = { workspace = true }
reqwest = { workspace = true }
scc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [
    "runtime-tokio",
    "sqlite",
    "postgres",
    "uuid",
    "migrate",
    "chrono",
] }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
wasmtime-wasi = { workspace = true, optional = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
test-r = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
tryhard = { workspace = true }
uuid = { workspace = true }

[[test]]
name = "integration"
path = "tests/lib.rs"
harness = false
