[package]
name = "golem-rust-tests"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'
strip = true

[dependencies]
golem-rust = { git = "https://github.com/golemcloud/golem-rust", branch = "type-owner" }
golem-rust-macro = { git = "https://github.com/golemcloud/golem-rust", branch = "type-owner" }
reqwest = { git = "https://github.com/zivergetech/reqwest", branch = "update-april-2025", features = ["json"] }
serde_json = "1.0.140"
wit-bindgen-rt = { version = "0.40.0", features = ["bitflags"] }

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
