[package]
name = "golem-rust-tests"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'
strip = true

[dependencies]
golem-rust = { version = "0.4.0" }
golem-rust-macro = { version = "0.4.0" }
reqwest = { git = "https://github.com/zivergetech/reqwest", branch = "update-jun-2024", features = ["json"] }
wit-bindgen-rt = { version = "0.26.0", features = ["bitflags"] }

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
