[package]
name = "golem-worker-executor-base"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem"
description = "Golem Worker Executor base implementation"

autotests = false


[lib]
path = "src/lib.rs"

[features]
mocks = []

[dependencies]
golem-common = { path = "../golem-common", version = "0.0.0" }
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0" }
golem-wasm-rpc = { workspace = true }

anyhow = { workspace = true }
async-fs = "2.1.0"
async-mutex = "1.4.0"
async-stream = { version = "0.3", optional = true }
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
bincode = { workspace = true }
bitflags = "2.4.2"
bytes = { workspace = true }
cap-fs-ext = "2.0.0" # keep in sync with wasmtime
cap-std = "2.0.0" # keep in sync with wasmtime
cap-time-ext = "2.0.0" # keep in sync with wasmtime
chrono = { workspace = true }
dashmap = { workspace = true }
figment = { workspace = true }
flume = "0.11.0"
fred = { workspace = true }
fs-set-times = "0.20.1"
futures = { workspace = true }
futures-util = { workspace = true }
gethostname = "0.4.3"
#golem-wit = { version = "0.2.4" }
golem-wit = { git="https://github.com/golemcloud/golem-wit.git", branch = "invoke" }
http = { workspace = true }
http_02 = { workspace = true }
http-body = "1.0.0" # keep in sync with wasmtime
humantime-serde = { workspace = true }
hyper = { workspace = true }
io-extras = "0.18.0"
iso8601-timestamp = { workspace = true }
lazy_static = { workspace = true }
log = "0.4.20"
metrohash = "1.0.6"
prometheus = { workspace = true }
prost = { workspace = true }
ringbuf = "0.3.3"
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tonic-reflection = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
warp = { workspace = true }
wasmtime = { version = "=17.0.0", features = ["component-model"] }
wasmtime-runtime = { version = "=17.0.0" }
wasmtime-wasi = { version = "=17.0.0" }
wasmtime-wasi-http = { version = "=17.0.0" }
windows-sys = "0.52.0"

[dev-dependencies]
golem-test-framework = { path = "../golem-test-framework", version = "0.0.0" }

assert2 = "0.3.11"
console-subscriber = { workspace = true }
ctor = "0.2.6"
fred = { workspace = true, features = ["metrics", "serde-json", "partial-tracing", "mocks"] }
golem-wasm-ast = { workspace = true }
proptest = { workspace = true }
redis = { version = "0.25.2", features = ["default"] }
serde_json = { workspace = true }
testcontainers = { version = "0.15.0", features = ["async-trait", "tokio"] }
tracing-subscriber = { workspace = true }
warp = { workspace = true }

[build-dependencies]
cargo_metadata = "0.18.1"

[[test]]
name = "integration"
path = "tests/lib.rs"
