[package]
name = "golem-worker-executor-base"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
description = "Golem Worker Executor base implementation"

autotests = false


[lib]
path = "src/lib.rs"

[features]
mocks = []

[dependencies]
golem-common = { path = "../golem-common", version = "0.0.0" }
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0" }

anyhow = { workspace = true }
async-mutex = "1.4.0"
async-stream = { version = "0.3", optional = true }
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
bincode = { workspace = true }
bitflags = "2.4.1"
bytes = { workspace = true }
cap-std = "2.0.0"
cap-time-ext = "2.0.0"
chrono = { workspace = true }
dashmap = "5.5.0"
figment = { workspace = true }
flume = "0.11.0"
fred = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
http-body = "1.0.0-rc.2"
humantime-serde = { workspace = true }
hyper = { workspace = true }
io-extras = "0.18.0"
iso8601-timestamp = "0.2.11"
lazy_static = { workspace = true }
log = "0.4.17"
prometheus = { workspace = true }
prost = { workspace = true }
ringbuf = "0.3.3"
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = "3.8.1"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tonic-reflection = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
value-bag = "1.4.2"
warp = { workspace = true }
wasmtime = { version = "=15.0.0", features = ["component-model"] }
wasmtime-runtime = { version = "=15.0.0" }
wasmtime-wasi = { version = "=15.0.0" }
wasmtime-wasi-http = { version = "=15.0.0" }
windows-sys = "0.52.0"

[dev-dependencies]
assert2 = "0.3.11"
console-subscriber = { workspace = true }
ctor = "0.2.6"
fred = { workspace = true, features = ["metrics", "serde-json", "partial-tracing", "mocks"] }
redis = { version = "0.24.0", features = ["default"] }
serde_json = { workspace = true }
tracing-subscriber = { workspace = true }
warp = { workspace = true }

[[test]]
name = "integration"
path = "tests/lib.rs"
