[package]
name = "golem-worker-executor-base"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem"
description = "Golem Worker Executor base implementation"

autotests = false


[lib]
path = "src/lib.rs"

[features]
mocks = []

[dependencies]
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0" }
golem-common = { path = "../golem-common", version = "0.0.0" }
golem-rib = { path = "../golem-rib", version = "0.0.0" }
golem-wasm-ast = { workspace = true }
golem-wasm-rpc = { workspace = true }

anyhow = { workspace = true }
async-fs = "2.1.0"
async-mutex = "1.4.0"
async-stream = { version = "0.3", optional = true }
async-trait = { workspace = true }
aws-config = { workspace = true }
aws-sdk-s3 = { workspace = true }
bincode = { workspace = true }
bitflags = "2.4.2"
bytes = { workspace = true }
cap-fs-ext = "3.0.0"                                # keep in sync with wasmtime
cap-std = { workspace = true }
cap-time-ext = "3.0.0"                              # keep in sync with wasmtime
chrono = { workspace = true }
dashmap = { workspace = true }
evicting_cache_map = "0.4.0"
figment = { workspace = true }
flume = "0.11.0"
fred = { workspace = true }
fs-set-times = "0.20.1"
futures = { workspace = true }
futures-util = { workspace = true }
gethostname = "0.4.3"
golem-wit = { version = "0.3.0" }
http = { workspace = true }
http_02 = { workspace = true }
http-body = "1.0.0"                                 # keep in sync with wasmtime
humansize = "2.1.3"
humantime-serde = { workspace = true }
hyper = { workspace = true }
io-extras = "0.18.0"
iso8601-timestamp = { workspace = true }
lazy_static = { workspace = true }
log = "0.4.20"
md5 = "0.7.0"
metrohash = "1.0.6"
nonempty-collections = "0.2.5"
prometheus = { workspace = true }
prost = { workspace = true }
ringbuf = "0.3.3"
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sysinfo = "0.30.12"
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
tonic-reflection = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }
warp = { workspace = true }
wasmtime = { workspace = true }
wasmtime-wasi = { workspace = true }
wasmtime-wasi-http = { workspace = true }
windows-sys = "0.52.0"
zstd = "0.13"

[dev-dependencies]
golem-test-framework = { path = "../golem-test-framework", version = "0.0.0" }

assert2 = { workspace = true }
console-subscriber = { workspace = true }
ctor = { workspace = true }
golem-wasm-ast = { workspace = true }
once_cell = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
redis = { workspace = true }
serde_json = { workspace = true }
testcontainers = { workspace = true }
testcontainers-modules = { workspace = true }
tracing-subscriber = { workspace = true }
warp = { workspace = true }

[build-dependencies]
cargo_metadata = "0.18.1"

[[test]]
name = "integration"
path = "tests/lib.rs"
