enable_tracing_console = false
enable_json_log = false

grpc_address = "0.0.0.0"
http_address = "0.0.0.0"

[oplog]
max_operations_before_commit = 128
operations_to_load = 128
debug_enabled = false

[limits]
max_active_instances = 1024
concurrency_limit_per_connection = 1024
max_concurrent_streams = 1024
event_broadcast_capacity = 16
event_history_size = 128
fuel_to_borrow = 10000
epoch_interval = "10ms"
epoch_ticks = 1

[retry]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[template_cache]
max_capacity = 32
time_to_idle = "12h"

[template_service]
type = "Grpc"

[template_service.config]
max_template_size = 52428800 # 50 Mb

# host
# port
# access_token

[template_service.config.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[compiled_template_service]
type = "S3"

[compiled_template_service.config]
object_prefix = ""
# region
# bucket

[compiled_template_service.config.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[blob_store_service]
type = "S3"

[blob_store_service.config]
bucket_prefix = ""
# region

[blob_store_service.config.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[key_value_service]
type = "Redis"

[resource_limits]
type = "Grpc"

[resource_limits.config]
# host
# port
# access_token
batch_update_interval = "1m"

[resource_limits.config.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[redis]
# host
# port
database = 0
tracing = false
pool_size = 8
key_prefix = ""

[redis.retries]
max_attempts = 5
min_delay = "100ms"
max_delay = "2s"
multiplier = 2

[shard_manager_service]
type = "Grpc"

[shard_manager_service.config]
# host
# port

[shard_manager_service.config.retries]
max_attempts = 5
min_delay = "100ms"
max_delay = "2s"
multiplier = 2

[scheduler]
refresh_interval = "2s"

[suspend]
suspend_after = "10s"

[active_workers]
drop_when_full = 0.25
ttl = "8h"

[promises]
type = "Redis"

[workers]
type = "Redis"

[invocation_keys]
pending_key_retention = "1m"
confirm_queue_capacity = 1024

[public_worker_api]
# host
# port
# access_token