enable_tracing_console = false
enable_json_log = false
# workspace
# environment
port = 9000
custom_request_port = 9001
worker_grpc_port = 9092

[memory]
# system_memory_override = 4294967296
worker_memory_ratio = 0.8
worker_estimate_coefficient = 1.1

[key_value_storage]
type = "Redis"

[key_value_storage.config]
# host
# port
database = 0
tracing = false
pool_size = 8
key_prefix = ""

[key_value_storage.config.retries]
max_attempts = 5
min_delay = "100ms"
max_delay = "2s"
multiplier = 2

[indexed_storage]
type = "KVStoreRedis"

[blob_storage]
type = "S3"

[blob_storage.config]
# region
# aws_endpoint_url
object_prefix = ""
compilation_cache_bucket = "compilation-cache"
custom_data_bucket = "custom-data"
oplog_payload_bucket = "oplog-payload"
compressed_oplog_buckets = ["oplog-archive-1"]
use_minio_credentials = false

[blob_storage.config.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[component_service]
# host
# port

[component_cache]
max_capacity = 0
time_to_idle = "1h"

[component_service.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[worker_executor_client_cache]
max_capacity = 1000
time_to_idle = "4h"

[routing_table]
# host
# port