[package]
name = "shopping-cart-example"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'
strip = true

[dependencies]
once_cell = "1.17.1"
rand = "0.8.5"
wit-bindgen-rt = { version = "0.40.0", features = ["bitflags"] }

[package.metadata.component.target]
path = "wit"

[package.metadata.component.dependencies]

[package.metadata.component.target.dependencies]
"golem:api" = { path = "wit/deps/golem-1.x" }
"golem:rpc" = { path = "wit/deps/golem-rpc" }
"wasi:clocks" = { path = "wit/deps/clocks" }
"wasi:io" = { path = "wit/deps/io" }

[workspace]
