{{- if eq .Values.ingress.type "nginx" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golem-services-{{.Values.env}}
  labels:
    env: {{.Values.env}}
{{- if .Values.ingress.nginx.annotations }}
  annotations: {{- .Values.ingress.nginx.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: "/v1/api"
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-worker-service-{{.Values.env}}
                port:
                  number: {{ .Values.workerService.ports.http }}
          - path: "/v2/components/[^/]+/workers/[^/]+/connect$"
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-worker-service-{{.Values.env}}
                port:
                  number: {{ .Values.workerService.ports.http }}
          - path: "/v2/components/[^/]+/workers(.*)"
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-worker-service-{{.Values.env}}
                port:
                  number: {{ .Values.workerService.ports.http }}
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-component-service-{{.Values.env}}
                port:
                  number: {{ .Values.componentService.ports.http }}
{{- end }}

{{- if eq .Values.ingress.type "alb" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golem-services-{{.Values.env}}
  labels:
    env: {{.Values.env}}
{{- if .Values.ingress.alb.annotations }}
  annotations: {{- .Values.ingress.alb.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: "/v1/api"
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-worker-service-{{.Values.env}}
                port:
                  number: {{ .Values.workerService.ports.http }}
          - path: "/v2/components/*/workers/*/connect"
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-worker-service-{{.Values.env}}
                port:
                  number: {{ .Values.workerService.ports.http }}
          - path: "/v2/components/*/workers/*"
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-worker-service-{{.Values.env}}
                port:
                  number: {{ .Values.workerService.ports.http }}
          - path: "/v2/components/*/workers"
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-worker-service-{{.Values.env}}
                port:
                  number: {{ .Values.workerService.ports.http }}
          - path: "/*"
            pathType: ImplementationSpecific
            backend:
              service:
                name: service-component-service-{{.Values.env}}
                port:
                  number: {{ .Values.componentService.ports.http }}
{{- end }}