apiVersion: v1
kind: Service
metadata:
  name: service-shard-manager-{{.Values.env}}
  labels:
    app: shard-manager-app-{{.Values.env}}
    env: {{.Values.env}}
spec:
  type: {{ .Values.shardManager.service.type }}
  selector:
    app: shard-manager-app-{{.Values.env}}
  ports:
    - protocol: TCP
      name: grpc
      port: {{ .Values.shardManager.ports.grpc }}
      targetPort: {{ .Values.shardManager.ports.grpc }}
    - protocol: TCP
      name: http
      port: {{ .Values.shardManager.ports.http }}
      targetPort: {{ .Values.shardManager.ports.http }}
---

apiVersion: v1
kind: Service
metadata:
  name: service-worker-executor-{{.Values.env}}
  labels:
    app: worker-executor-app-{{.Values.env}}
    env: {{.Values.env}}
spec:
  type: {{ .Values.workerExecutor.service.type }}
  selector:
    app: worker-executor-app-{{.Values.env}}
  ports:
    - protocol: TCP
      name: grpc
      port: {{ .Values.workerExecutor.ports.grpc }}
      targetPort: {{ .Values.workerExecutor.ports.grpc }}
    - protocol: TCP
      name: http
      port: {{ .Values.workerExecutor.ports.http }}
      targetPort: {{ .Values.workerExecutor.ports.http }}
---

apiVersion: v1
kind: Service
metadata:
  name: service-worker-service-{{.Values.env}}
  labels:
    app: worker-service-app-{{.Values.env}}
    env: {{.Values.env}}
spec:
  type: {{ .Values.workerService.service.type }}
  selector:
    app: worker-service-app-{{.Values.env}}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.workerService.ports.http }}
      targetPort: {{ .Values.workerService.ports.http }}
    - protocol: TCP
      name: rhttp
      port: {{ .Values.workerService.ports.requestHttp }}
      targetPort: {{ .Values.workerService.ports.requestHttp }}
    - protocol: TCP
      name: grpc
      port: {{ .Values.workerService.ports.grpc }}
      targetPort: {{ .Values.workerService.ports.grpc }}
---

apiVersion: v1
kind: Service
metadata:
  name: service-template-service-{{.Values.env}}
  labels:
    app: template-service-app-{{.Values.env}}
    env: {{.Values.env}}
spec:
  type: {{ .Values.templateService.service.type }}
  selector:
    app: template-service-app-{{.Values.env}}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.templateService.ports.http }}
      targetPort: {{ .Values.templateService.ports.http }}
    - protocol: TCP
      name: grpc
      port: {{ .Values.templateService.ports.grpc }}
      targetPort: {{ .Values.templateService.ports.grpc }}
