# workspace
environment = "local"

port = 9005
custom_request_port = 9006
worker_grpc_port = 9007

[redis]
host = "localhost"
port = 6380
database = 1
tracing = false
pool_size = 8
key_prefix = ""

[redis.retries]
max_attempts = 5
min_delay = "100ms"
max_delay = "2s"
multiplier = 2

[component_service]
host = "localhost"
port = 9090
access_token = "5C832D93-FF85-4A8F-9803-513950FDFDB1"

[component_service.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3

[worker_executor_client_cache]
max_capacity = 1000
time_to_idle = "4h"

[routing_table]
host = "localhost"
port = 9002
