[package]
name = "parent-component"
version = "0.0.1"
edition = "2021"
homepage = "https://golem.cloud"
license = "Apache-2.0"

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies."golem:it"]
path = "wit/deps/golem_it"

[package.metadata.component.target.dependencies."golem:it-stub"]
path = "wit/deps/golem_it-stub"

[package.metadata.component.target.dependencies."golem:rpc"]
path = "wit/deps/wasm-rpc"

[dependencies]
once_cell = "1.17.1"
rand = "0.8.5"

[dependencies.common]
path = "../../common"

[dependencies.wit-bindgen]
version = "0.17.0"
features = ["realloc"]
default-features = false

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
required-features = []

[profile.release]
opt-level = "s"
lto = true
strip = true
