enable_tracing_console = false
enable_json_log = false
# workspace
# environment
management_port = 9000
port = 9001

[redis]
# host
# port
database = 0
tracing = false
pool_size = 8
key_prefix = ""

[redis.retries]
max_attempts = 5
min_delay = "100ms"
max_delay = "2s"
multiplier = 2

[template_service]
# host
# port
# access_token

[template_service.retries]
max_attempts = 3
min_delay = "100ms"
max_delay = "1s"
multiplier = 3
