[package]
name = "golem-it-http-client"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'
strip = true

[dependencies]
golem-wasi-http = { version = "0.1.0", features = ["async", "json"] }
async-iterator = { version = "2.3.0" }
futures-concurrency = "7.6.3"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
wasi = "=0.14.1+wasi-0.2.3"
wstd = {version = "=0.5.4", features = ["default", "json"] }
wit-bindgen-rt = { version = "0.40.0", features = ["bitflags"] }

[package.metadata.component]
package = "golem:it"

[package.metadata.component.target]
path = "wit"
