[package]
name = "golem-api-grpc"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem"
description = "GRPC API for Golem services"

[lib]

[dependencies]
async-trait = { workspace = true }
bincode = { workspace = true }
bytes = { workspace = true }
futures-core = { workspace = true }
golem-wasm-rpc = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }


[build-dependencies]
cargo_metadata = "0.18.1"
tonic-build = "0.11.0"
