[package]
name = "template-service"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "template-service"
path = "src/server.rs"

[[bin]]
name = "template-service-yaml"
path = "src/openapi_yaml.rs"

[lib]

[dependencies]
golem-common = { path = "../golem-common", version = "0.0.0" }
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0" }
golem-service-base = { path = "../golem-service-base" }
golem-wasm-rpc = { path = "../wasm-rpc/wasm-rpc", default-features = false, features = ["host"] }

async-trait = { workspace = true }
console-subscriber = { workspace = true }
golem-wasm-ast = { workspace = true }
mappable-rc = "0.1.1"
figment = { workspace = true }
futures-util = { workspace = true }
lazy_static = { workspace = true }
poem = { workspace = true, features = ["prometheus", "opentelemetry"] }
poem-openapi = { workspace = true }
prometheus = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry-prometheus = { workspace = true }
opentelemetry_sdk = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite", "postgres", "uuid" , "migrate", "chrono"] }
tap = "1.0.1"
tonic = { workspace = true }
tonic-health = { workspace = true }
tonic-reflection = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = "0.7.10"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
humantime-serde = { workspace = true }
