[package]
name = "golem-rib"
version = "0.0.0"
edition = "2021"

homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem"
description = "Parser for Golem's Rib language"

license-file = "../LICENSE"

[features]
default = ["json_in_errors", "protobuf", "poem"]
json_in_errors = ["protobuf", "golem-wasm-rpc/json"]
protobuf = [
    "dep:golem-api-grpc",
    "golem-wasm-ast/protobuf",
    "golem-wasm-rpc/protobuf",
]
poem = [
    "dep:poem-openapi",
    "golem-wasm-ast/poem_openapi",
    "golem-wasm-rpc/poem_openapi",
]

[dependencies]
golem-api-grpc = { workspace = true, optional = true } # TODO: remove this dependency
golem-wasm-ast = { workspace = true, features = ["analysis", "bincode"] }
golem-wasm-rpc = { workspace = true, features = ["bincode", "typeinfo", "text"] }

async-trait = { workspace = true }
bigdecimal = { workspace = true }
bincode = { workspace = true }
combine = { workspace = true }
poem-openapi = { workspace = true, optional = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
test-r = { workspace = true }

[lib]
name = "rib"
path = "src/lib.rs"
harness = false


[[test]]
name = "rib_regression"
path = "regression_tests/lib.rs"
harness = false
