[package]
name = "golem-rib"
version = "0.0.0"
edition = "2021"

homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem"
description = "Parser for Golem's Rib language"

license-file = "../LICENSE"

[features]
default = ["json_in_errors", "poem"]
json_in_errors = []
poem = [
    "dep:poem-openapi",
]

[dependencies]
golem-wasm = { workspace = true }

async-trait = { workspace = true }
bigdecimal = { workspace = true }
combine = { workspace = true }
desert_rust = { workspace = true }
lazy_static = { workspace = true }
poem-openapi = { workspace = true, optional = true }
prost = { workspace = true }
prost-types = { workspace = true }
semver = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { workspace = true }
tonic-prost = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
cargo_metadata = { workspace = true }
miette = { workspace = true }
protox = { workspace = true }
tonic-prost-build = { workspace = true }

[dev-dependencies]
test-r = { workspace = true }

[lib]
name = "rib"
path = "src/lib.rs"
harness = false


[[test]]
name = "rib_regression"
path = "regression_tests/lib.rs"
harness = false
