[package]
name = "golem-rib"
version = "0.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://golem.cloud"
repository = "https://github.com/golemcloud/golem"
description = "Parser for Golem's Rib language"

[dependencies]
golem-api-grpc = { path = "../golem-api-grpc", version = "0.0.0", optional = true }

bincode = { workspace = true }
combine = { workspace = true }
golem-wasm-ast = { workspace = true, default-features = false }
golem-wasm-rpc = { workspace = true, default-features = false }
poem-openapi = { workspace = true, optional = true }
semver = "1.0.23"
serde = { workspace = true }
serde_json = { workspace = true }
wasm-wave = { workspace = true }

[dev-dependencies]
test-r = { workspace = true }

[lib]
name = "rib"
path = "src/lib.rs"
harness = false

[features]
default = []
full = ["dep:golem-api-grpc"]
poem = ["dep:poem-openapi"]