[package]
name = "logging"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'

[dependencies]
wit-bindgen-rt = { version = "0.40.0", features = ["bitflags"] }

golem-rust = { git = "https://github.com/golemcloud/golem-rust", branch = "type-owner" }
golem-rust-macro = { git = "https://github.com/golemcloud/golem-rust", branch = "type-owner" }
log = { version = "0.4.22", features = ["kv"] }
rand = "0.8.5"
reqwest = { git = "https://github.com/zivergetech/reqwest", branch = "update-march-2025", features = [
    "json",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wasi-logger = { version = "0.1.2", features = ["kv"] }

[package.metadata.component.target]
path = "wit"

[package.metadata.component.target.dependencies]
