version: '3'

services:
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT}:6379

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: golem_db
      POSTGRES_USER: golem_user
      POSTGRES_PASSWORD: golem_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  golem-shard-manager:
    image: golemservices/golem-shard-manager:latest
    environment:
      - REDIS_HOST=redis
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__REDIS__HOST=redis
      - GOLEM__REDIS__PORT=${REDIS_PORT}
      - GOLEM__HTTP_PORT=${SHARD_MANAGER_HTTP_PORT}
      - GOLEM_SHARD_MANAGER_PORT=${SHARD_MANAGER_GRPC_PORT}
    depends_on:
      - redis

  golem-cloud-server-oss:
    image: golemservices/golem-server:latest
    environment:
      - ENVIRONMENT=local
      - RUST_LOG="debug,h2=warn,hyper=warn,tower=warn"
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__TEMPLATES__STORE__TYPE="Local"
      - GOLEM__TEMPLATES__STORE__CONFIG__OBJECT_PREFIX=""
      - GOLEM__TEMPLATES__STORE__CONFIG__ROOT_PATH=/template_store
      - GOLEM__DB__TYPE=Postgres
      - GOLEM__DB__CONFIG__DATABASE=golem_db
      - GOLEM__DB__CONFIG__MAX_CONNECTIONS=10
      - GOLEM__DB__CONFIG__HOST=postgres
      - GOLEM__DB__CONFIG__USERNAME=golem_user
      - GOLEM__DB__CONFIG__PASSWORD=golem_password
      - GOLEM__ROUTING_TABLE__HOST="golem-shard-manager"
      - GOLEM__ROUTING_TABLE__PORT=${SHARD_MANAGER_GRPC_PORT}
      - GOLEM__GRPC_PORT=${CLOUD_SERVER_GRPC_PORT}
      - GOLEM__HTTP_PORT=${CLOUD_SERVER_HTTP_PORT}
    volumes:
      - template_store:/template_store
    ports:
      - "${CLOUD_SERVER_HTTP_PORT}:${CLOUD_SERVER_HTTP_PORT}"
      - "${CLOUD_SERVER_GRPC_PORT}:${CLOUD_SERVER_GRPC_PORT}"

  golem-worker-executor-oss:
    image: golemservices/golem-worker-executor:latest
    environment:
      - ENVIRONMENT=local
      - RUST_LOG=info
      - WASMTIME_BACKTRACE_DETAILS=1
      - RUST_BACKTRACE=1
      - GOLEM__REDIS__PORT=${REDIS_PORT}
      - GOLEM__REDIS__HOST=redis
      - GOLEM__TEMPLATE_SERVICE__CONFIG__HOST=golem-cloud-server-oss
      - GOLEM__TEMPLATE_SERVICE__CONFIG__PORT=${CLOUD_SERVER_GRPC_PORT}
      - GOLEM__TEMPLATE_SERVICE__CONFIG__ACCESS_TOKEN="2A354594-7A63-4091-A46B-CC58D379F677"
      - GOLEM__PORT=${WORKER_EXECUTOR_GRPC_PORT}
      - GOLEM__HTTP_PORT=${WORKER_EXECUTOR_HTTP_PORT}
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__HOST=golem-shard-manager
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__PORT=${SHARD_MANAGER_GRPC_PORT}
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_ATTEMPTS=5
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MIN_DELAY="100ms"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MAX_DELAY="2s"
      - GOLEM__SHARD_MANAGER_SERVICE__CONFIG__RETRIES__MULTIPLIER=2
      - GOLEM__BLOB_STORE_SERVICE__CONFIG__REGION=us-east-1
      - GOLEM__COMPILED_TEMPLATE_SERVICE__CONFIG__ROOT="data/templates"
      - GOLEM__COMPILED_TEMPLATE_SERVICE__TYPE="Local"
      - GOLEM__SHARD_MANAGER_SERVICE__TYPE="Grpc"
      - AWS_SECRET_ACCESS_KEY=root
      - AWS_ACCESS_KEY_ID=root
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "${WORKER_EXECUTOR_HTTP_PORT}:${WORKER_EXECUTOR_HTTP_PORT}"

volumes:
  redis_data:
    driver: local
  template_store:
    driver: local
  postgres_data:
    driver: local