[package]
name = "golem_it_ifs_update_inside_exported_function"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
required-features = []

[dependencies]
# To use common shared libs, use the following:
# common-lib = { path = "../../common-rust/common-lib" }

golem-wasi-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
wit-bindgen-rt = { workspace = true }

[package.metadata.component.target]
path = "wit-generated"

[package.metadata.component.target.dependencies]
"wasi:io" = { path = "wit-generated/deps/io" }
"wasi:clocks" = { path = "wit-generated/deps/clocks" }
"wasi:random" = { path = "wit-generated/deps/random" }
"wasi:filesystem" = { path = "wit-generated/deps/filesystem" }
"wasi:sockets" = { path = "wit-generated/deps/sockets" }
"wasi:cli" = { path = "wit-generated/deps/cli" }
"wasi:http" = { path = "wit-generated/deps/http" }
"golem-it:ifs-update-inside-exported-function-exports" = { path = "wit-generated/deps/golem-it_ifs-update-inside-exported-function-exports" }

[package.metadata.component.bindings]
# See https://github.com/bytecodealliance/cargo-component/blob/main/src/metadata.rs#L62

# derives = ["serde::Serialize", "serde::Deserialize"]
# generate_unused_types = true
